from flask import Flask, request
import requests
from flask_cors import CORS
from urllib.request import urlopen

app = Flask(__name__)
CORS(app)

# @param url The url that hosts the dreamup app
#
# Returns an html string generated by the model for the given dreamup app url
@app.route('/', methods=['POST'])
def url_to_html():
    req_json = request.get_json()

    #
    # fetch dreamup app data
    #
    dreamup_app_url = req_json['url']

    # Right now the dreamup assumes every app will have an instructions.txt file
    # which contains all of the natural language instructions required to construct the app.
    # Eventually this will not be a requirement and the browser will need to infer the app's
    # structure given arbitrary content in the directory.
    instructions_url = (
        dreamup_app_url + 'instructions.txt' if dreamup_app_url.endswith('/')
        else dreamup_app_url + '/instructions.txt'
    )
    dreamup_app_req = requests.get(instructions_url)
    instructions = dreamup_app_req.text

    # request results from our lang->html model
    model_endpoint = 'http://localhost:8082'
    model_query_url = ("{0}?instructions={1}").format(model_endpoint, instructions)
    model_response = requests.get(model_endpoint, { 'instructions': instructions })

    return model_response.text
